# Generated by Django 4.0.2 on 2022-07-26 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(max_length=400, null=True)),
                ('addressrss', models.CharField(max_length=400, null=True)),
                ('x_path', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('image', models.URLField(null=True)),
                ('directlink', models.URLField(max_length=400, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two')], default=0)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.feed')),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
